import * as ROUTES from '@/router/routes.js'

export const convertersList = [
  {
    title: 'Units',
    description: 'Convert length, weight, temperature, and more.',
    name: ROUTES.UNIT.name,
    href: ROUTES.UNIT.path,
    isDisabled: false,
  },
  {
    title: 'Dates',
    description: 'Age calculator, days between dates, week numbers, and more.',
    name: ROUTES.DATE.name,
    href: ROUTES.DATE.path,
    isDisabled: false,
  },
  {
    title: 'Time',
    description: 'Convert time zones, durations, timestamps, and more.',
    name: ROUTES.TIME.name,
    href: ROUTES.TIME.path,
    isDisabled: false,
  },
  {
    title: 'Currency',
    description: 'Live exchange rates, historical conversions, crypto to fiat.',
    name: ROUTES.CURRENCY.name,
    href: ROUTES.CURRENCY.path,
    isDisabled: false,
  },
  {
    title: 'Math',
    description: 'Fractions to decimals, Roman numerals, percentages.',
    name: ROUTES.MATH.name,
    href: ROUTES.MATH.path,
    isDisabled: false,
  },
  {
    title: 'Text',
    description: 'Uppercase/lowercase, ASCII to text, character count.',
    name: ROUTES.TEXT.name,
    href: ROUTES.TEXT.path,
    isDisabled: false,
  },
  {
    title: 'Digital Storage',
    description: 'Convert between KB, MB, GB, TB, and more.',
    name: ROUTES.DIGITAL_STORAGE.name,
    href: ROUTES.DIGITAL_STORAGE.path,
    isDisabled: false,
  },
  {
    title: 'Finance',
    description: 'Loan interest, tax calculator, inflation adjustment.',
    name: ROUTES.FINANCE.name,
    href: ROUTES.FINANCE.path,
    isDisabled: false,
  },
  {
    title: 'Science',
    description: 'Atomic mass, wavelength to frequency, radiation units.',
    name: ROUTES.SCIENCE.name,
    href: ROUTES.SCIENCE.path,
    isDisabled: false,
  },
  {
    title: 'Engineering',
    description: 'Torque, power, viscosity, thermal conductivity.',
    name: ROUTES.ENGINEERING.name,
    href: ROUTES.ENGINEERING.path,
    isDisabled: false,
  },
  {
    title: 'Health & Fitness',
    description: 'BMI calculator, calorie burn, steps to distance.',
    name: ROUTES.HEALTH.name,
    href: ROUTES.HEALTH.path,
    isDisabled: false,
  },
  {
    title: 'Geography',
    description: 'GPS coordinates, latitude/longitude distance, country codes.',
    name: ROUTES.GEOGRAPHY.name,
    href: ROUTES.GEOGRAPHY.path,
    isDisabled: false,
  },
  {
    title: 'Miscellaneous',
    description:
      'Aspect ratio calculator, Shoe size conversion, cooking measurements, dice roll probability',
    name: ROUTES.MISC.name,
    href: ROUTES.MISC.path,
    isDisabled: false,
  },
]
