export const convertersList = [
  {
    title: 'Units',
    name: 'units',
    description: 'Convert length, weight, temperature, and more.',
    href: '/units',
    isDisabled: true,
  },
  {
    title: 'Dates',
    name: 'dates',
    description: 'Age calculator, days between dates, week numbers, and more.',
    href: '/dates',
    isDisabled: true,
  },
  {
    title: 'Time',
    name: 'time',
    description: 'Convert time zones, durations, timestamps, and more.',
    href: '/time',
    isDisabled: true,
  },
  {
    title: 'Currency',
    name: 'currency',
    description: 'Live exchange rates, historical conversions, crypto to fiat.',
    href: '/currency',
    isDisabled: true,
  },
  {
    title: 'Math',
    name: 'math',
    description: 'Fractions to decimals, Roman numerals, percentages.',
    href: '/math',
    isDisabled: true,
  },
  {
    title: 'Text',
    name: 'text',
    description: 'Uppercase/lowercase, ASCII to text, character count.',
    href: '/text',
    isDisabled: true,
  },
  {
    title: 'Digital Storage',
    name: 'digital-storage',
    description: 'Convert between KB, MB, GB, TB, and more.',
    href: '/digital-storage',
    isDisabled: true,
  },
  {
    title: 'Finance',
    name: 'finance',
    description: 'Loan interest, tax calculator, inflation adjustment.',
    href: '/finance',
    isDisabled: true,
  },
  {
    title: 'Science',
    name: 'science',
    description: 'Atomic mass, wavelength to frequency, radiation units.',
    href: '/science',
    isDisabled: true,
  },
  {
    title: 'Engineering',
    name: 'engineering',
    description: 'Torque, power, viscosity, thermal conductivity.',
    href: '/engineering',
    isDisabled: true,
  },
  {
    title: 'Health & Fitness',
    name: 'health-fitness',
    description: 'BMI calculator, calorie burn, steps to distance.',
    href: '/health-fitness',
    isDisabled: true,
  },
  {
    title: 'Geography',
    name: 'geography',
    description: 'GPS coordinates, latitude/longitude distance, country codes.',
    href: '/geography',
    isDisabled: true,
  },
  {
    title: 'Miscellaneous',
    name: 'miscellaneous',
    description:
      'Shoe size conversion, cooking measurements, dice roll probability.',
    href: '/miscellaneous',
    isDisabled: true,
  },
]
